import { nestedId, optionalNumber, toNumber } from './resourceUtils'

export const bookingStatuses = [
  'PENDING',
  'CONFIRMED',
  'CHECKED_IN',
  'CHECKED_OUT',
  'CANCELLED',
  'NO_SHOW',
]

function profileFields(includePassword) {
  return [
    { name: 'email', label: 'Email', type: 'email', required: true },
    includePassword && { name: 'password', label: 'Mật khẩu', type: 'password', required: true },
    { name: 'name', label: 'Họ tên', required: true },
    { name: 'phone', label: 'Số điện thoại', required: true },
    { name: 'address', label: 'Địa chỉ' },
    { name: 'image', label: 'Ảnh đại diện' },
  ].filter(Boolean)
}

export const resources = [
  {
    key: 'bookings',
    label: 'Đặt phòng',
    endpoint: '/bookings',
    description: 'Tạo booking, tính tiền theo bảng giá và cập nhật trạng thái.',
    fields: [
      { name: 'customerId', label: 'ID khách hàng', type: 'number', required: true },
      { name: 'employeeId', label: 'ID nhân viên', type: 'number' },
      { name: 'roomId', label: 'ID phòng', type: 'number', required: true },
      { name: 'checkIn', label: 'Check-in', type: 'datetime-local', required: true },
      { name: 'checkOut', label: 'Check-out', type: 'datetime-local', required: true },
      { name: 'guestCount', label: 'Số khách', type: 'number', required: true },
    ],
    buildPayload: (data) => ({
      customerId: toNumber(data.customerId),
      employeeId: optionalNumber(data.employeeId),
      roomId: toNumber(data.roomId),
      checkIn: data.checkIn,
      checkOut: data.checkOut,
      guestCount: toNumber(data.guestCount),
    }),
  },
  {
    key: 'customers',
    label: 'Khách hàng',
    endpoint: '/customers',
    description: 'Thông tin liên hệ và tài khoản khách hàng.',
    fields: profileFields(true),
  },
  {
    key: 'employees',
    label: 'Nhân viên',
    endpoint: '/employees',
    description: 'Nhân sự vận hành homestay, có liên kết vai trò.',
    fields: [
      { name: 'name', label: 'Họ tên', required: true },
      { name: 'salary', label: 'Lương', type: 'number' },
      { name: 'email', label: 'Email', type: 'email', required: true },
      { name: 'password', label: 'Mật khẩu', type: 'password', required: true },
      { name: 'phone', label: 'Số điện thoại', required: true },
      { name: 'address', label: 'Địa chỉ' },
      { name: 'image', label: 'Ảnh đại diện' },
      { name: 'roleId', label: 'ID vai trò', type: 'number' },
    ],
    buildPayload: (data) => ({
      name: data.name,
      salary: optionalNumber(data.salary),
      email: data.email,
      password: data.password,
      phone: data.phone,
      address: data.address,
      image: data.image,
      role: nestedId(data.roleId),
    }),
  },
  {
    key: 'branches',
    label: 'Chi nhánh',
    endpoint: '/branches',
    description: 'Cơ sở homestay, địa chỉ, hotline và ảnh đại diện.',
    fields: [
      { name: 'name', label: 'Tên chi nhánh', required: true },
      { name: 'address', label: 'Địa chỉ', required: true },
      { name: 'phone', label: 'Số điện thoại', required: true },
      { name: 'image', label: 'Anh' },
    ],
  },
  {
    key: 'roomTypes',
    label: 'Loại phòng',
    endpoint: '/roomTypes',
    description: 'Loại phòng, sức chứa và mô tả.',
    fields: [
      { name: 'name', label: 'Tên loại phòng', required: true },
      { name: 'description', label: 'Mô tả' },
      { name: 'maxGuest', label: 'Số khách tối đa', type: 'number', required: true },
      { name: 'image', label: 'Anh' },
    ],
    buildPayload: (data) => ({
      name: data.name,
      description: data.description,
      maxGuest: toNumber(data.maxGuest),
      image: data.image,
    }),
  },
  {
    key: 'rooms',
    label: 'Phòng',
    endpoint: '/rooms',
    description: 'Phòng thực tế gắn với chi nhánh và loại phòng.',
    fields: [
      { name: 'branchId', label: 'ID chi nhánh', type: 'number', required: true },
      { name: 'roomTypeId', label: 'ID loại phòng', type: 'number', required: true },
      { name: 'name', label: 'Tên phòng', required: true },
      { name: 'area', label: 'Diện tích', type: 'number', required: true },
      { name: 'thumbnail', label: 'Ảnh phòng' },
    ],
    buildPayload: (data) => ({
      branchId: toNumber(data.branchId),
      roomTypeId: toNumber(data.roomTypeId),
      name: data.name,
      area: Number(data.area || 0),
      thumbnail: data.thumbnail,
    }),
  },
  {
    key: 'roomPricings',
    label: 'Bảng giá',
    endpoint: '/roomPricings',
    description: 'Giá ngày thường, cuối tuần, ngày lễ theo loại phòng.',
    fields: [
      { name: 'roomTypeId', label: 'ID loại phòng', type: 'number', required: true },
      { name: 'baseDuration', label: 'Đơn vị tính', placeholder: 'NIGHT', required: true },
      { name: 'basePrice', label: 'Giá cơ bản', type: 'number', required: true },
      { name: 'weekendPrice', label: 'Giá cuối tuần', type: 'number', required: true },
      { name: 'holidayPrice', label: 'Giá ngày lễ', type: 'number', required: true },
      { name: 'startDate', label: 'Bắt đầu', type: 'datetime-local', required: true },
      { name: 'endDate', label: 'Kết thúc', type: 'datetime-local' },
      { name: 'policy', label: 'Chính sách' },
      { name: 'status', label: 'Đang áp dụng', type: 'checkbox' },
    ],
    buildPayload: (data) => ({
      roomType: nestedId(data.roomTypeId),
      baseDuration: data.baseDuration,
      basePrice: optionalNumber(data.basePrice),
      weekendPrice: optionalNumber(data.weekendPrice),
      holidayPrice: optionalNumber(data.holidayPrice),
      startDate: data.startDate,
      endDate: data.endDate || null,
      policy: data.policy,
      status: Boolean(data.status),
    }),
  },
  {
    key: 'categories',
    label: 'Nhóm tiện ích',
    endpoint: '/categories',
    description: 'Nhóm phân loại tiện ích.',
    fields: [
      { name: 'name', label: 'Tên nhóm', required: true },
      { name: 'description', label: 'Mô tả' },
    ],
  },
  {
    key: 'amenities',
    label: 'Tiện ích',
    endpoint: '/amenities',
    description: 'Tiện ích gắn với nhóm tiện ích.',
    fields: [
      { name: 'categoryId', label: 'ID nhóm tiện ích', type: 'number' },
      { name: 'name', label: 'Tên tiện ích', required: true },
    ],
    buildPayload: (data) => ({
      category: nestedId(data.categoryId),
      name: data.name,
    }),
  },
  {
    key: 'roles',
    label: 'Vai trò',
    endpoint: '/roles',
    description: 'Vai trò nhân viên.',
    fields: [
      { name: 'name', label: 'Tên vai trò', required: true },
      { name: 'description', label: 'Mô tả' },
    ],
  },
  {
    key: 'roomPhotos',
    label: 'Ảnh phòng',
    endpoint: '/roomPhotos',
    description: 'Ảnh bổ sung cho phòng.',
    fields: [
      { name: 'roomId', label: 'ID phòng', type: 'number', required: true },
      { name: 'photo', label: 'Anh', required: true },
    ],
    buildPayload: (data) => ({
      roomId: toNumber(data.roomId),
      photo: data.photo,
    }),
  },
]
